"""
Blocksize Agentic Buyer Simulation

This script demonstrates how an AI Agent connected to a CDP (Coinbase Developer Platform) wallet
interacts with the Blocksize x402 edge node. 

In a production environment, you would inject your `CDP_API_KEY_NAME` and `CDP_API_KEY_PRIVATE_KEY` 
environment variables so the agent can execute the real USDC transfer.

Usage:
    python scripts/agent_buyer.py
"""

import asyncio
import base64
import json
import time

import httpx

# The live URL of your deployed Blocksize server
RAILWAY_URL = "https://agentic-payments-production.up.railway.app"
ENDPOINT = f"{RAILWAY_URL}/v1/vwap/BTC-USD"

async def run_agent():
    print(f"🤖 [Agent]: Waking up. I need the latest BTC-USD VWAP data.")
    
    async with httpx.AsyncClient() as client:
        # 1. The Agent requests data without paying
        print(f"🤖 [Agent]: Requesting data from {ENDPOINT}...")
        response = await client.get(ENDPOINT)
        
        if response.status_code == 402:
            print(f"⛔️ [Server]: 402 Payment Required intercepted.")
            
            # 2. Parse the invoice
            invoice_b64 = response.headers.get("PAYMENT-REQUIRED")
            invoice = json.loads(base64.b64decode(invoice_b64).decode())
            
            # We pick the Solana requirement (the first one)
            solana_req = invoice[0]
            amount_micro_usdc = int(solana_req["maxAmountRequired"])
            amount_usdc = amount_micro_usdc / 1_000_000
            pay_to = solana_req["payTo"]
            
            print(f"🤖 [Agent]: Parsed Invoice. I need to pay ${amount_usdc} USDC to Solana wallet {pay_to}")
            
            # 3. Simulate the CDP Wallet Transfer
            print(f"🤖 [Agent]: Inititating CDP Wallet transaction on Solana network...")
            time.sleep(1.5) # Simulating network latency
            
            mock_tx_hash = "5TzG3xyz...ThisIsWhereTheRealTxHashGoes"
            print(f"✅ [Agent]: Transaction confirmed! Hash: {mock_tx_hash}")
            
            # 4. Generate the cryptographic signature payload combining the TX + Agent's private key
            print(f"🤖 [Agent]: Cryptographically signing the exact HTTP request...")
            
            # MOCK SIGNATURE (In reality, this is generated by x402-sdk or agentkit)
            mock_signed_payload = {
                "proof": mock_tx_hash,
                "network": solana_req["network"],
                "timestamp": int(time.time()),
                "agent_pubkey": "EPeD8xyz...",
                "signature": "MOCK_SIGNATURE_DATA"
            }
            signature_header = base64.b64encode(json.dumps(mock_signed_payload).encode()).decode()
            
            # 5. Resubmit request containing the signature
            print(f"🤖 [Agent]: Re-requesting data with PAYMENT-SIGNATURE attached...")
            
            final_response = await client.get(
                ENDPOINT,
                headers={"PAYMENT-SIGNATURE": signature_header}
            )
            
            if final_response.status_code == 200:
                print(f"🎉 [Server]: Payment Verified! Payload unlocked.")
                print(f"📊 [Data]: \n{json.dumps(final_response.json(), indent=2)}")
            else:
                # With our placeholder facilitator, verification will fail here in reality
                print(f"⛔️ [Server]: {final_response.status_code} - {final_response.text}")
                print(f"\n💡 Note: In this simulation, the server rejected the MOCK signature because the Facilitator could not find '{mock_tx_hash}' on the Solana blockchain. A real AgentKit setup would generate a real transaction hash!")
                
        else:
            print(f"Unexpected response: {response.status_code}")

if __name__ == "__main__":
    asyncio.run(run_agent())
