"""Hard upper bounds for durable x402 response replay."""

MAX_CACHED_PAYMENT_RESPONSE_BYTES = 512 * 1024
MAX_PAYMENT_REPLAY_TTL_SECONDS = 3_600
MAX_PAYMENT_REPLAY_ENTRIES = 500


__all__ = [
    "MAX_CACHED_PAYMENT_RESPONSE_BYTES",
    "MAX_PAYMENT_REPLAY_ENTRIES",
    "MAX_PAYMENT_REPLAY_TTL_SECONDS",
]
